apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJpbmRleC5kb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJhbmlrZXQ1MjQiLCJwYXNzd29yZCI6IlBhc3NANzU4OCIsImVtYWlsIjoiYW5pa2V0a2FycDUyNEBnbWFpbC5jb20ifX19

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend
  labels:
    app:  frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app:  frontend
    spec:
      containers:
      - name:  frontend
        image: aniket524/privateimage:50
        ports:
        - containerPort:  3000
      imagePullSecrets:
      - name: dockerhub-secret
      
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000




